### ISSUE TITLE
上传 显示太多

### ISSUE THREAD

**Issue by heimanba** [devsapp/start-website#5]
![image](https://user-images.githubusercontent.com/5129967/115644337-ff3f9400-a350-11eb-8bd6-cbe53b578ee6.png)

所有成功的显示在一行，失败的需要单独显示，或者直接退出

**Comment by xsahxl** [comment]
所有成功的显示在一行, 如果上传的文件太少，比如三个文件，上传速度很快就只显示了一个 最后上传的文件。目前采取上传成功后 把spinner停止掉。所有文件上传成功后 提示 OSS静态资源部署成功
